name: build_grpc_channel
description: The util builds gRPC channel for flutter web or other platforms conditionally, depending on the runtime environment
version: 0.5.0
homepage: https://github.com/premiumapp-org/build_grpc_channel

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  grpc: ^3.0.2
